# Generated by Django 4.1 on 2023-03-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
