# Generated by Django 4.1 on 2023-03-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_user_employee_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
