# Generated by Django 4.1 on 2023-03-02 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_csv_download'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csv_download',
            name='user',
        ),
    ]
