# Generated by Django 4.1 on 2023-03-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_user_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_token',
            field=models.CharField(default='1111', max_length=100),
            preserve_default=False,
        ),
    ]
